name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: npm test

  release:
    runs-on: ubuntu-18.04
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: docker build -t hofnarwillie/http200ok:$GITHUB_SHA -t hofnarwillie/http200ok:latest .
    - name: Login
      run: echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login --username hofnarwillie --password-stdin
    - name: Push Docker Image
      run: |
        docker push hofnarwillie/http200ok:$GITHUB_SHA
        docker push hofnarwillie/http200ok:latest